apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mycroft-app-tls
spec:
  secretName: mycroft-app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mycroft.app
  dnsNames:
    - mycroft.app
    - www.mycroft.app
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mycroft.app
          - www.mycroft.app
